import type { Metadata } from 'next'
import { Barlow } from 'next/font/google'
import './globals.css'
import Nav from './views/Nav'

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={barlow.className}>{children}</body>
    </html>
  )
}
